export const ActionTypes = {
     SET_CATEGORIES: "SET_CATEGORIES",
     SET_WISHLIST: "SET_WISHLIST",
    SET_CART: "SET_CART",
    UPDATE_CART: "UPDATE_CART",
     UPDATE_WISHLIST_CART: "UPDATE_WISHLIST_CART",
     RESET_STORE: "RESET_STORE",
     SET_PRODUCTS: "SET_PRODUCTS",
     SET_SUBCATEGORIES: "SET_SUBCATEGORIES",
    
  };
  